### ISSUE TITLE
New note should start an edit window directly

### ISSUE THREAD

**Issue by erickr** [charlesthomas/magpie#47]
Currently, the user first have to name the note before starting taking notes. 

I propose to change the flow to be:
1. Click New note
2. Full textarea for editing(autosave should work here to)
3. Name the note, preferrably in a field below the textarea. 
4. Save

Would also be great if we could auto-suggest a name for the note after the notes have been added. NvPy takes whatever is on the first line of the note, makes sense more often than you can think. :)

**Comment by tony-o** [comment]
Blast from the past
