### ISSUE TITLE
Encoding issues still - internal server error 500

### ISSUE THREAD

**Issue by erickr** [charlesthomas/magpie#51]
We are still having encoding issues at different places as it seems.

The following reproduces one issue:
1. Create notebook containing utf8 characters, for example "testnotebook åäö"
2. Create a note containing utf8 characters, for example "test åäö"
3. Add a few tasks to the note, for example:
  [ ] task 1
  [ ] task 2
4. Save
5. Try to edit the note, and on save the internal server error shows.

Have seen a few more but need to detail the way to reproduce them. Whats the state of python 3, is it reasonable to use that as a requirement instead of 2.7, if it at all might help us here?

**Comment by tony-o** [comment]
This issue was resolved - please close
