### ISSUE TITLE
git submodule dependency failure

### ISSUE THREAD

**Issue by Erwyn** [charlesthomas/magpie#54]
I have this in my terminal, and if I go to the repository url, there's no link to checkout…:

```
Clone of 'https://github.com/domchristie/to-markdown.git' into submodule path 'magpie/static/js/to-markdown' failed
```

**Comment by tony-o** [comment]
@Erwyn are you still having this issue?

**Comment by Erwyn** [comment]
I think we can close this as the project is more or less abandonned.
