### ISSUE TITLE
Automated Travis test misconfigured

### ISSUE THREAD

**Issue by jamesscottbrown** [charlesthomas/magpie#63]
All of the pull requests are marked as having failed tests, because Travis is misconfigured: it is trying to run tests with a git identify set, [resulting in failures like](https://travis-ci.org/charlesthomas/magpie/builds/49020080):

    ErrorReturnCode_128:

    RAN: '/usr/bin/git commit -m creating /tmp/magpie_testing_git_repo/git_tests/new_note'

    STDOUT:

    STDERR:

    *** Please tell me who you are.

    Run

    git config --global user.email "you@example.com"

    git config --global user.name "Your Name"

    to set your account's default identity.

    Omit --global to set the identity only in this repository.

    fatal: empty ident name (for <travis@testing-worker-linux-f25aadab-1-1616-linux-5-49020081.(none)>) not allowed

**Comment by charlesthomas** [comment]
fixed by #65
