### ISSUE TITLE
Demo offline

### ISSUE THREAD

**Issue by almereyda** [charlesthomas/magpie#73]
I wanted to get an impression of Magpie, but unfortunately the demo is offline.
How does it look like?

**Comment by cooperra** [comment]
Took some screenshots :camera: 

Home

![image](https://cloud.githubusercontent.com/assets/659057/10985609/b1718a38-83f0-11e5-86b1-2d43d73fdb10.png)

A notebook

![image](https://cloud.githubusercontent.com/assets/659057/10985637/ed7677c8-83f0-11e5-9e65-c258558dacb9.png)

New note

![image](https://cloud.githubusercontent.com/assets/659057/10985651/0fc951e2-83f1-11e5-8f73-24fec4eab25d.png)

View note

![image](https://cloud.githubusercontent.com/assets/659057/10985658/1f39deee-83f1-11e5-9f60-79d7d86bb792.png)

Edit note

![image](https://cloud.githubusercontent.com/assets/659057/10985675/438b9738-83f1-11e5-9395-91da0f981594.png)

Edited note

![image](https://cloud.githubusercontent.com/assets/659057/10985691/60ea7178-83f1-11e5-8582-77d6365e2bf9.png)

Hope these help. :)

**Comment by Hugins-Bote** [comment]
atm I get Error 530, when I try to reach the demo

**Comment by charlesthomas** [comment]
There's a security flaw in magpie where you can break out of the magpie directory and view the whole file system.

I had to offline the demo until that's fixed, but it's no longer under active development.
